### ISSUE TITLE
$A ft_strchrでせぐふぉ

### ISSUE THREAD

**Issue by syamashi** [syamashi/minishell#143]
$A=NULLの場合。
```
 [KO] "$A"

Your exit status : 134
Expected exit status : 0

 [KO] "$OLDPWD"

Your exit status : 134
Expected exit status : 0

 [KO] "<test1.txt"

Your exit status : 134
Expected exit status : 0

 [KO] "<test1.txt<test2.txt<test3.txt<test4.txt"

Your exit status : 134
Expected exit status : 0
```

**Comment by syamashi** [comment]
makefileにfsanitize=addressを追加したことによる発見かも。
提出前に解除予定。

**Comment by syamashi** [comment]
```
the zero page.
    #0 0x10063faaa in ft_memcpy (minishell:x86_64+0x10000aaaa)
    #1 0x10063b905 in make_path ft_execvpe.c:26
    #2 0x10063b71d in sh_execvpe ft_execvpe.c:47
    #3 0x10063d121 in sh_execvpes sh_launch_utils.c:17
    #4 0x10063d51c in sh_launch_child sh_launch.c:50
    #5 0x10063d5ef in sh_process_manager sh_launch.c:67
    #6 0x10063d7d7 in sh_launch sh
    ```

**Comment by syamashi** [comment]
fix
https://github.com/syamashi/minishell/commit/ebdac26e23f9c7c8b6410ae42ad80b6cd5584c77
