### ISSUE TITLE
[wc | 1<file]セグフォ

### ISSUE THREAD

**Issue by syamashi** [syamashi/minishell#149]
```
c1r1s6% ./minishell
wc | 1<file
AddressSanitizer:DEADLYSIGNAL
=================================================================
==49829==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010d411794 bp 0x7ff
ee27f48c0 sp 0x7ffee27f4760 T0)
==49829==The signal is caused by a READ memory access.
==49829==Hint: address points to the zero page.
    #0 0x10d411793 in sh_execvpe ft_execvpe.c:55
    #1 0x10d413101 in sh_execvpes sh_launch_utils.c:17
    #2 0x10d4134fc in sh_launch_child sh_launch.c:50
    #3 0x10d4135cf in sh_process_manager sh_launch.c:67
    #4 0x10d4136d1 in sh_process_manager sh_launch.c:78
    #5 0x10d4137da in sh_launch sh_launch.c:96
    #6 0x10d40d8e8 in minishell minishell.c:107
    #7 0x10d40c491 in main main.c:19
    #8 0x7fff68e5e3d4 in start (libdyld.dylib:x86_64+0x163d4)
```

**Comment by syamashi** [comment]
fix
https://github.com/syamashi/minishell/commit/07a4e8e537c4962f3371d8700df202495d74f1f2
